set(MITK_VERSION "2024.06")
set(MITK_DIR ${CMAKE_CURRENT_BINARY_DIR}/MITK-build)

ExternalProject_Add(MITK
  GIT_REPOSITORY "https://github.com/MITK/MITK.git"
  GIT_TAG        "v${MITK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/MITK
  BINARY_DIR     ${MITK_DIR}
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DVTK_DIR:PATH=${VTK_DIR}
    -DITK_DIR:PATH=${ITK_DIR}
    -DQt6_DIR:PATH=${Qt6_DIR}
    -DGDCM_DIR:PATH=${GDCM_DIR}
    -DHDF5_DIR:PATH=${HDF5_DIR}
    -DMITK_BUILD_EXAMPLES:BOOL=OFF
    -DMITK_BUILD_TESTING:BOOL=OFF
  INSTALL_COMMAND ""
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
  DEPENDS VTK ITK GDCM HDF5
)
