set(VMTK_INSTALL_DIR ${CMAKE_BINARY_DIR}/VMTK-install)
set(VMTK_DIR ${VMTK_INSTALL_DIR}/lib)

set(VMTK_Qt_ARGS "")
if(SV_BUILD_QT)
  set(VMTK_Qt_ARGS -DQt6_DIR:PATH=${Qt6_DIR})
endif()

ExternalProject_Add(VMTK
  GIT_REPOSITORY "https://github.com/vmtk/vmtk.git"
  GIT_TAG        "ba7cf0f61bd826a18600234c37c49be878eb932e"
  GIT_SHALLOW    FALSE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/VMTK
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/VMTK-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${VMTK_INSTALL_DIR}
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DVMTK_USE_SUPERBUILD:BOOL=OFF
    -DVMTK_USE_RENDERING:BOOL=ON
    -DVMTK_USE_ITK:BOOL=ON
    -DUSE_SYSTEM_VTK:BOOL=ON
    -DVTK_DIR:PATH=${VTK_DIR}
    -DUSE_SYSTEM_ITK:BOOL=ON
    -DITK_DIR:PATH=${ITK_DIR}
    ${VMTK_Qt_ARGS}
    -DVMTK_BUILD_TESTING:BOOL=OFF
    -DVMTK_BUILD_TETGEN:BOOL=OFF
    -DVTK_VMTK_WRAP_PYTHON:BOOL=OFF
    -DVMTK_WRAP_PYTHON:BOOL=OFF
    -DVMTK_SCRIPTS_ENABLED:BOOL=ON
  INSTALL_DIR ${VMTK_INSTALL_DIR}
  DEPENDS VTK ITK
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
