set(ITK_VERSION "5.4.0")
set(ITK_DIR ${CMAKE_CURRENT_BINARY_DIR}/ITK-build)

ExternalProject_Add(ITK
  GIT_REPOSITORY "https://github.com/InsightSoftwareConsortium/ITK.git"
  GIT_TAG        "v${ITK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/ITK
  BINARY_DIR     ${ITK_DIR}
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DBUILD_EXAMPLES:BOOL=OFF
    -DITK_BUILD_DEFAULT_MODULES:BOOL=ON
    -DITK_USE_GPU:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DITK_USE_SYSTEM_GDCM:BOOL=ON
    -DGDCM_DIR:PATH=${GDCM_DIR}
  INSTALL_COMMAND ""
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
  DEPENDS GDCM
)
