set(MITK_VERSION "2024.06")
set(MITK_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/MITK-build/)
set(MITK_DIR ${MITK_BINARY_DIR}/MITK-build)

ExternalProject_Add(MITK
  GIT_REPOSITORY "https://github.com/MITK/MITK.git"
  GIT_TAG        "v${MITK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/MITK
  BINARY_DIR     ${MITK_BINARY_DIR}
  PATCH_COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=<SOURCE_DIR> -P ${CMAKE_CURRENT_SOURCE_DIR}/PatchMITKQElapsedTimer.cmake
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DVTK_DIR:PATH=${VTK_DIR}
    -DMITK_USE_SYSTEM_VTK:BOOL=ON
    -DITK_DIR:PATH=${ITK_DIR}
    -DMITK_USE_SYSTEM_ITK:BOOL=ON
    -DQt6_DIR:PATH=${Qt6_DIR}
    -DGDCM_DIR:PATH=${GDCM_DIR}
    -DHDF5_ROOT:PATH=${HDF5_INSTALL_DIR}
    -DHDF5_DIR:PATH=${HDF5_DIR}
    -DMITK_USE_SYSTEM_HDF5:BOOL=ON
    -DMITK_BUILD_EXAMPLES:BOOL=OFF
    -DMITK_BUILD_TESTING:BOOL=OFF
    -DMITK_BUILD_CONFIGURATION:STRING=Custom
    -DMITK_USE_MatchPoint:BOOL=OFF
    -DEXTERNAL_GDCM_DIR:PATH=${GDCM_DIR}
    -DEXTERNAL_ITK_DIR:PATH=${ITK_DIR}
    -DEXTERNAL_VTK_DIR:PATH=${VTK_DIR}
    -DMITK_USE_DCMQI:BOOL=OFF
  CMAKE_CACHE_ARGS
    "-DMITK_ADDITIONAL_CXX_FLAGS:STRING=-Wno-error=overloaded-virtual -Wno-error=unused-result"
  INSTALL_COMMAND ""
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
  DEPENDS VTK ITK GDCM HDF5
)
