set(OpenCASCADE_VERSION "7.6.0")
set(OpenCASCADE_INSTALL_DIR ${CMAKE_BINARY_DIR}/OpenCASCADE-install)
set(OpenCASCADE_DIR ${OpenCASCADE_INSTALL_DIR}/lib/cmake/opencascade)

ExternalProject_Add(OpenCASCADE
  GIT_REPOSITORY "https://github.com/Open-Cascade-SAS/OCCT.git"
  GIT_TAG        "V7_6_0"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/OpenCASCADE
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/OpenCASCADE-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${OpenCASCADE_INSTALL_DIR}
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DBUILD_MODULE_Draw:BOOL=OFF
    -DBUILD_MODULE_Visualization:BOOL=ON
    -DBUILD_MODULE_ApplicationFramework:BOOL=ON
    -DBUILD_TESTING:BOOL=OFF
    -DUSE_VTK:BOOL=ON
    -D3RDPARTY_VTK_DIR:PATH=${VTK_INSTALL_DIR}
    -D3RDPARTY_VTK_INCLUDE_DIR:PATH=${VTK_INSTALL_DIR}/include/vtk-9.3
    -D3RDPARTY_VTK_LIBRARY_DIR:PATH=${VTK_INSTALL_DIR}/lib
    -DINSTALL_DIR_LIB:STRING=lib
    -DINSTALL_DIR_INCLUDE:STRING=include/opencascade
  INSTALL_DIR ${OpenCASCADE_INSTALL_DIR}
  DEPENDS VTK
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
