set(ITK_VERSION "5.4.0")
set(ITK_INSTALL_DIR ${CMAKE_BINARY_DIR}/ITK-install)
set(ITK_DIR ${ITK_INSTALL_DIR}/lib/cmake/ITK-5.4)

ExternalProject_Add(ITK
  GIT_REPOSITORY "https://github.com/InsightSoftwareConsortium/ITK.git"
  GIT_TAG        "v${ITK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/ITK
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/ITK-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${ITK_INSTALL_DIR}
    -DBUILD_EXAMPLES:BOOL=OFF
    -DITK_BUILD_DEFAULT_MODULES:BOOL=ON
    -DITK_USE_GPU:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DITK_USE_SYSTEM_GDCM:BOOL=ON
    -DGDCM_DIR:PATH=${GDCM_DIR}
    -DITK_USE_SYSTEM_HDF5:BOOL=ON
    -DHDF5_ROOT:PATH=${HDF5_INSTALL_DIR}
    -DHDF5_DIR:PATH=${HDF5_DIR}
    -DModule_ITKReview=1
    -DModule_ITKVtkGlue=1
    -DModule_GrowCut:BOOL=ON
    -DVTK_DIR:PATH=${VTK_DIR}
    -DQt6_DIR:PATH=${Qt6_DIR}
  INSTALL_DIR ${ITK_INSTALL_DIR}
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
  DEPENDS GDCM HDF5 VTK
)
