set(VTK_VERSION "9.3.1")
set(VTK_DIR ${CMAKE_CURRENT_BINARY_DIR}/VTK-build)

ExternalProject_Add(VTK
  GIT_REPOSITORY "https://github.com/VTK/VTK.git"
  GIT_TAG        "v${VTK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/VTK
  BINARY_DIR     ${VTK_DIR}
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DVTK_BUILD_TESTING:BOOL=OFF
    -DVTK_BUILD_EXAMPLES:BOOL=OFF
    -DVTK_BUILD_DOCUMENTATION:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  INSTALL_COMMAND ""
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
