set(VTK_VERSION "9.3.1")
set(VTK_INSTALL_DIR ${CMAKE_BINARY_DIR}/VTK-install)
set(VTK_DIR ${VTK_INSTALL_DIR}/lib/cmake/vtk-9.3)

ExternalProject_Add(VTK
  GIT_REPOSITORY "https://gitlab.kitware.com/vtk/vtk.git"
  GIT_TAG        "v${VTK_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/VTK
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/VTK-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${VTK_INSTALL_DIR}
    -DVTK_BUILD_TESTING:BOOL=OFF
    -DVTK_BUILD_EXAMPLES:BOOL=OFF
    -DVTK_BUILD_DOCUMENTATION:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DVTK_SMP_IMPLEMENTATION_TYPE:STRING=Sequential
    -DVTK_GROUP_ENABLE_Qt:STRING=YES
    -DVTK_QT_VERSION:STRING=6
    -DQt6_DIR:PATH=${Qt6_DIR}
    -DVTK_WRAP_PYTHON:BOOL=ON
    -DPython_EXECUTABLE:PATH=${Python_EXECUTABLE}
  INSTALL_DIR ${VTK_INSTALL_DIR}
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
