set(GDCM_VERSION "3.0.10")
set(GDCM_INSTALL_DIR ${CMAKE_BINARY_DIR}/GDCM-install)
set(GDCM_DIR ${GDCM_INSTALL_DIR}/lib/gdcm-3.0)

ExternalProject_Add(GDCM
  GIT_REPOSITORY "https://github.com/malaterre/GDCM.git"
  GIT_TAG        "v${GDCM_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/GDCM
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/GDCM-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${GDCM_INSTALL_DIR}
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DGDCM_BUILD_TESTING:BOOL=OFF
    -DGDCM_BUILD_EXAMPLES:BOOL=OFF
    -DGDCM_USE_VTK:BOOL=OFF
    -DGDCM_BUILD_APPLICATIONS=1
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true
    -DGDCM_BUILD_DOCBOOK_MANPAGES=0
  INSTALL_DIR ${GDCM_INSTALL_DIR}
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
