set(TetGen_VERSION "1.5.1")
set(TetGen_INSTALL_DIR ${CMAKE_BINARY_DIR}/TetGen-install)
set(TETGEN_INCLUDE_DIR ${TetGen_INSTALL_DIR}/include)
set(TETGEN_LIBRARY ${TetGen_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}tet${CMAKE_STATIC_LIBRARY_SUFFIX})

ExternalProject_Add(TetGen
  GIT_REPOSITORY "https://github.com/TetGen/TetGen.git"
  GIT_TAG        "v${TetGen_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/TetGen
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/TetGen-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${TetGen_INSTALL_DIR}
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
  INSTALL_COMMAND
    ${CMAKE_COMMAND} -E make_directory ${TetGen_INSTALL_DIR}/include ${TetGen_INSTALL_DIR}/lib
    COMMAND ${CMAKE_COMMAND} -E copy
      ${CMAKE_CURRENT_BINARY_DIR}/TetGen/tetgen.h
      ${TetGen_INSTALL_DIR}/include/tetgen.h
    COMMAND ${CMAKE_COMMAND} -E copy
      ${CMAKE_CURRENT_BINARY_DIR}/TetGen-build/${CMAKE_CFG_INTDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}tet${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${TETGEN_LIBRARY}
  INSTALL_DIR ${TetGen_INSTALL_DIR}
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
