set(MMG_VERSION "5.3.9")
set(MMG_INSTALL_DIR ${CMAKE_BINARY_DIR}/MMG-install)
set(MMG_DIR ${MMG_INSTALL_DIR}/lib/cmake/mmg)
set(MMG_INCLUDE_DIR ${MMG_INSTALL_DIR}/include)

ExternalProject_Add(MMG
  GIT_REPOSITORY "https://github.com/MmgTools/mmg.git"
  GIT_TAG        "v${MMG_VERSION}"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/MMG
  BINARY_DIR     ${CMAKE_CURRENT_BINARY_DIR}/MMG-build
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DCMAKE_INSTALL_PREFIX:PATH=${MMG_INSTALL_DIR}
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DLIBMMG2D_SHARED:BOOL=OFF
    -DLIBMMG3D_SHARED:BOOL=OFF
    -DLIBMMGS_SHARED:BOOL=OFF
    -DLIBMMG_SHARED:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DCMAKE_C_FLAGS:STRING=-fcommon
  INSTALL_DIR ${MMG_INSTALL_DIR}
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
