set(HDF5_VERSION "1.14.3")
set(HDF5_DIR ${CMAKE_BINARY_DIR}/HDF5-install/share/cmake/hdf5)

ExternalProject_Add(HDF5
  GIT_REPOSITORY "https://github.com/HDFGroup/hdf5.git"
  GIT_TAG        "hdf5-1_14_3"
  GIT_SHALLOW    TRUE
  GIT_PROGRESS   TRUE
  SOURCE_DIR     ${CMAKE_CURRENT_BINARY_DIR}/HDF5
  BINARY_DIR     ${HDF5_DIR}
  CMAKE_ARGS
    ${ep_common_cmake_args}
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DHDF5_BUILD_CPP_LIB:BOOL=ON
    -DHDF5_BUILD_HL_LIB:BOOL=ON
    -DHDF5_BUILD_TOOLS:BOOL=OFF
    -DHDF5_BUILD_EXAMPLES:BOOL=OFF
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
  INSTALL_DIR ${CMAKE_BINARY_DIR}/HDF5-install
  USES_TERMINAL_DOWNLOAD 1
  USES_TERMINAL_UPDATE   1
  USES_TERMINAL_BUILD    1
)
